{
  "dependences": {},
  "targetObject": "1e438eca-7a4c-4e98-b1c4-a7fd3100a61f",
  "targetLocked": true,
  "loop": true,
  "samples": 60,
  "playEventInEditor": true,
  "name": "attackA",
  "eventList": "[]",
  "propertyList": {
    "/SpriteA": {
      "10": [
        [
          7,
          [
            [
              0,
              "idle"
            ],
            [
              25,
              "atk2"
            ],
            [
              110,
              "idle"
            ]
          ]
        ]
      ]
    },
    "/": {
      "1": [
        [
          2,
          [
            [
              0,
              0,
              0,
              7.6644
            ],
            [
              30,
              229.932,
              7.6644,
              -0.04202083333333325
            ],
            [
              78,
              227.915,
              -0.04202083333333325,
              -7.12234375
            ],
            [
              110,
              0,
              -7.12234375,
              0
            ],
            [
              0,
              0
            ]
          ]
        ],
        [
          2,
          [
            [
              0,
              0,
              0,
              0.0336
            ],
            [
              30,
              1.008,
              0.0336,
              0
            ],
            [
              78,
              1.008,
              0,
              -0.0315
            ],
            [
              110,
              0,
              -0.0315,
              0
            ],
            [
              0,
              0
            ]
          ]
        ]
      ]
    }
  }
}
