{
  "dependences": {},
  "targetObject": "c4535457-89fd-49bb-a19d-7fdd4be583df",
  "targetLocked": true,
  "loop": false,
  "samples": 60,
  "playEventInEditor": true,
  "name": "damageB",
  "eventList": "[]",
  "propertyList": {
    "/SpriteB": {
      "10": [
        [
          7,
          [
            [
              0,
              "damage"
            ],
            [
              40,
              "idle"
            ]
          ]
        ]
      ]
    },
    "/UIText": {
      "1": [
        [
          2,
          [
            [
              0,
              558.6949152872002,
              0,
              -0.000022882180005012742
            ],
            [
              40,
              558.694,
              -0.000022882180005012742,
              0.000018305744004010193
            ],
            [
              0,
              0
            ]
          ]
        ],
        [
          2,
          [
            [
              0,
              146.22881336626477,
              0,
              -0.5546703341566193
            ],
            [
              40,
              124.042,
              -0.5546703341566193,
              0.4437362673252954
            ],
            [
              0,
              0
            ]
          ]
        ]
      ],
      "3": [
        [
          2,
          [
            [
              0,
              0.3,
              0,
              0.017499999999999998
            ],
            [
              40,
              1,
              0.017499999999999998,
              -0.02127659574468085
            ],
            [
              87,
              0,
              -0.02127659574468085,
              -0.02127659574468085
            ],
            [
              0,
              0
            ]
          ]
        ]
      ],
      "6": [
        [
          5,
          [
            [
              0,
              true
            ],
            [
              90,
              false
            ]
          ]
        ]
      ]
    }
  }
}
