{
  "dependences": {},
  "targetObject": "1e438eca-7a4c-4e98-b1c4-a7fd3100a61f",
  "targetLocked": true,
  "loop": false,
  "samples": 60,
  "playEventInEditor": true,
  "name": "diedA",
  "eventList": "[]",
  "propertyList": {
    "/UIText": {
      "1": [
        [
          2,
          [
            [
              0,
              97.822,
              0,
              -0.000025000000000119372
            ],
            [
              40,
              97.821,
              -0.000025000000000119372,
              0
            ],
            [
              87,
              97.821,
              0,
              0
            ],
            [
              0,
              0
            ]
          ]
        ],
        [
          2,
          [
            [
              0,
              146.229,
              0,
              -0.0004250000000006082
            ],
            [
              40,
              146.212,
              -0.0004250000000006082,
              -0.5360638297872339
            ],
            [
              87,
              121.017,
              -0.5360638297872339,
              0
            ],
            [
              0,
              0
            ]
          ]
        ]
      ],
      "3": [
        [
          2,
          [
            [
              0,
              0.3,
              0,
              0.06363636363636363
            ],
            [
              11,
              1,
              0.06363636363636363,
              0
            ],
            [
              40,
              1,
              0,
              -0.02127659574468085
            ],
            [
              87,
              0,
              -0.02127659574468085,
              -0.02127659574468085
            ],
            [
              0,
              0
            ]
          ]
        ]
      ],
      "4": [
        [
          2,
          [
            [
              0,
              1,
              0,
              0.05454545454545456
            ],
            [
              11,
              1.6,
              0.05454545454545456,
              0.05454545454545456
            ],
            [
              0,
              0
            ]
          ]
        ],
        [
          2,
          [
            [
              0,
              1,
              0,
              0.05454545454545456
            ],
            [
              11,
              1.6,
              0.05454545454545456,
              0.05454545454545456
            ],
            [
              0,
              0
            ]
          ]
        ]
      ],
      "6": [
        [
          5,
          [
            [
              0,
              true
            ],
            [
              90,
              false
            ]
          ]
        ]
      ]
    },
    "/SpriteA": {
      "10": [
        [
          7,
          [
            [
              0,
              "damage"
            ],
            [
              40,
              "death"
            ]
          ]
        ]
      ]
    }
  }
}
