{
  "dependences": {},
  "id": 1,
  "targetObject": "81e85262-17e1-47f2-af30-cdc55ae2fde7",
  "targetLocked": false,
  "loop": false,
  "samples": 60,
  "name": "unlocked",
  "scripts": [],
  "propertyList": {
    "/": {
      "14": [
        [
          1,
          [
            [
              0,
              0,
              21.49999999999995,
              21.49999999999995
            ],
            [
              25,
              308,
              0,
              0
            ],
            [
              50,
              0,
              -23.499999999999964,
              -23.499999999999964
            ],
            [
              0,
              0
            ]
          ]
        ],
        [
          1,
          [
            [
              0,
              0,
              0,
              0
            ],
            [
              25,
              0,
              0,
              0
            ],
            [
              50,
              0,
              0,
              0
            ],
            [
              0,
              0
            ]
          ]
        ]
      ]
    }
  },
  "eventList": "[]"
}
