{
  "dependences": {},
  "id": 1,
  "targetObject": "81e85262-17e1-47f2-af30-cdc55ae2fde7",
  "targetLocked": false,
  "loop": false,
  "samples": 60,
  "name": "relative",
  "propertyList": {
    "/": {
      "1": [
        [
          1,
          [
            [
              0,
              0,
              0,
              12.8644
            ],
            [
              15,
              192.966,
              12.8644,
              7.834466666666667
            ],
            [
              45,
              428,
              7.834466666666667,
              11.469733333333336
            ],
            [
              60,
              600.046,
              11.469733333333336,
              11.469733333333334
            ],
            [
              0,
              0
            ]
          ]
        ],
        [
          1,
          [
            [
              0,
              0,
              0,
              -3.7874666666666674
            ],
            [
              15,
              -56.81200000000001,
              -3.7874666666666674,
              5.150733333333333
            ],
            [
              45,
              97.70999999999998,
              5.150733333333333,
              -6.549799999999999
            ],
            [
              60,
              -0.5370000000000061,
              -6.549799999999999,
              -6.549799999999999
            ],
            [
              0,
              0
            ]
          ]
        ]
      ]
    }
  },
  "eventList": "[[16,\"testEvent\",[\"12\",\"ab\"]],[23,\"testEvent\",[\"a\",\"b\",\"c\",\"d\"]],[97,\"testEvent2\",[]]]"
}
