{
  "dependences": {},
  "id": 1,
  "targetObject": "81e85262-17e1-47f2-af30-cdc55ae2fde7",
  "targetLocked": false,
  "loop": false,
  "samples": 60,
  "name": "tweenAbsolute",
  "propertyList": {
    "/": {
      "1": [
        [
          4,
          [
            [
              0,
              0,
              0,
              0.021439023008236035
            ],
            [
              15,
              0.32158534512354053,
              0.021439023008236035,
              0.013056443450446575
            ],
            [
              45,
              0.7132786486369378,
              0.013056443450446575,
              0.01911475675753748
            ],
            [
              60,
              1,
              0.01911475675753748,
              11.469733333333334
            ],
            [
              0,
              0
            ]
          ],
          [
            100,
            700.046
          ]
        ],
        [
          4,
          [
            [
              0,
              0,
              0,
              -0.038762323883601145
            ],
            [
              15,
              -0.5814348582540172,
              -0.038762323883601145,
              0.05271449527513391
            ],
            [
              45,
              1,
              0.05271449527513391,
              -0.06703305700542422
            ],
            [
              60,
              -0.005495855081363282,
              -0.06703305700542422,
              -6.549799999999999
            ],
            [
              0,
              0
            ]
          ],
          [
            200,
            297.71
          ]
        ]
      ]
    }
  },
  "eventList": "[[16,\"testEvent\",[\"12\",\"ab\"]],[23,\"testEvent\",[\"a\",\"b\",\"c\",\"d\"]],[97,\"testEvent2\",[]]]"
}
